python gradcam_single_image_seg.py \
    --checkpoint /mnt/wangbd8/workspace/ThyroidAgent/dino_unet_ori/checkpoints/baseline/dino_unet_train_dataset_4_epoch_50.pth \
    --image_path /mnt/wangbd8/workspace/DataSets/ThyroidAgent/Classifaction_Data/Lymph_Node_Metastasis_fake/images/22_Benign_center1.png \
    --mask_path /mnt/wangbd8/workspace/DataSets/ThyroidAgent/Classifaction_Data/Lymph_Node_Metastasis_fake/masks/22_Benign_center1.png \
    --output_dir ./pyradiomics_dice/gradcam/LNM_CN01 \
    --img_size 224 \
    --dino_pretrained True \
    --alpha 0.3 \
    --target_layer up1 \
    --smooth_sigma_ratio 0.02 \
    --gamma 1.0 \
    --saturation_scale 1.5
